version: '3.4'

services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    depends_on:
      - app
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db/pgdata:/var/lib/postgresql/data
