version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db/pgdata:/var/lib/postgresql/data

  broker:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
