# Generated by Django 4.1.6 on 2023-02-05 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="Endereço de email",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="País",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Rua",
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alameda", "ALAMEDA"),
                            ("avenida", "AVENIDA"),
                            ("chacara", "CHACARA"),
                            ("condominio", "CONDOMÍNIO"),
                            ("conjunto", "CONJUNTO"),
                            ("estrada", "ESTRADA"),
                            ("ladeira", "LADEIRA"),
                            ("largo", "LARGO"),
                            ("parque", "PARQUE"),
                            ("praca", "PRAÇA"),
                            ("praia", "PRAIA"),
                            ("quadra", "QUADRA"),
                            ("rodovia", "RODOVIA"),
                            ("rua", "RUA"),
                            ("travessa", "TRAVESSA"),
                            ("via", "VIA"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de endereço",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
                "db_table": "account_address",
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "usuário criado"),
                            ("POST_READ", "usuário viu publicação"),
                            ("POST_LIKE", "usuário curtiu publicação"),
                            ("EVENT_VIEW", "usuário viu um evento"),
                            ("EVENT_LIKE", "usuário viu um evento"),
                            ("BIBLE_VIEW", "usuário viu bíblia"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Origem",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico do Usuário",
                "verbose_name_plural": "Históricos dos Usuários",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Foto do Perfil",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biografia"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Homem"), (1, "Mulher"), (2, "-")],
                        default=2,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "cnh",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="CNH",
                    ),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="RG"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "income_bracket",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Faixa de renda",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Profissão",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Nascimento",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "SOLTEIRO"),
                            ("married", "CASADO"),
                            ("widower", "VIUVO"),
                            ("divorced", "DIVORCIADO"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "emitting_organ",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Orgão Emissor",
                    ),
                ),
                (
                    "expedition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Expedição"
                    ),
                ),
                (
                    "email_message_enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="Aceitar e-mails para comunicação?",
                    ),
                ),
                (
                    "phone_message_enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="Aceitar comunicação de celular",
                    ),
                ),
                (
                    "is_main_contact",
                    models.BooleanField(
                        default=False, verbose_name="É o contato principal"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to="account.address",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Informação Pessoal",
                "verbose_name_plural": "Informações Pessoais",
                "db_table": "account_profile",
            },
        ),
        migrations.CreateModel(
            name="ContactMeans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "WhatsApp"),
                            (2, "email"),
                            (3, "facebook"),
                            (4, "instagram"),
                            (5, "telefone"),
                        ],
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Contato"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Público"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma de Contato",
                "verbose_name_plural": "Formas de Contato",
            },
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["user", "created_at"],
                name="account_use_user_id_ce5cbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["category", "-created_at"],
                name="account_use_categor_f2a9ca_idx",
            ),
        ),
    ]
