# Generated by Django 4.1.6 on 2023-02-20 19:57

from django.db import migrations, models

import igreja.apps.account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="biography",
        ),
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Sobre"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Masculino"), (1, "Feminino")],
                default=2,
                null=True,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="imagem usada como perfil da conta",
                null=True,
                upload_to=igreja.apps.account.models.get_profile_image_upload_to,
                verbose_name="Perfil",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "solteiro"),
                    ("married", "casado"),
                    ("widower", "viúvo"),
                    ("divorced", "divorciado"),
                ],
                max_length=100,
                null=True,
                verbose_name="Estado Civil",
            ),
        ),
    ]
