# Generated by Django 4.1.6 on 2023-02-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_profile_biography_profile_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="new_events_alerts",
            field=models.BooleanField(
                default=True, verbose_name="informações sobre novos eventos"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="new_posts_alerts",
            field=models.BooleanField(
                default=True,
                verbose_name="informações sobre novos posts do blog",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="new_products_alerts",
            field=models.BooleanField(
                default=True,
                verbose_name="informações sobre novos produtos e serviços",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="security_alerts",
            field=models.BooleanField(
                default=True, verbose_name="Alertas de segurança"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="breve descrição do usuário",
                null=True,
                verbose_name="Sobre",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.CharField(
                blank=True,
                help_text="A sua profissão atual",
                max_length=100,
                null=True,
                verbose_name="Profissão",
            ),
        ),
    ]
