name: Dokku CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  DOKKU_HOST: 34.196.25.75
  DOKKU_APP_NAME: ibm-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to dokku
      id: deploy
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        remote-branch: main
        ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
        dokku-host: ${{ env.DOKKU_HOST }}
        app-name: ${{ env.DOKKU_APP_NAME }}
