name: Dokku CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOKKU_HOST: 34.196.25.75
  DOKKU_APP_NAME: ibm-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ibm-prod.danilokerolayne.tk
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: echo
      run: echo 'Dockku host ${{ env.DOKKU_HOST }}'

    - name: Deploy to dokku
      id: deploy
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        remote-branch: main
        git-push-flags: --force
        ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
        dokku-host: ${{ env.DOKKU_HOST }}
        app-name: ${{ env.DOKKU_APP_NAME }}
